services:
  - type: web
    name: foreas-stripe-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: PRICE_ID
        sync: false
      - key: SUCCESS_URL
        sync: false
      - key: CANCEL_URL
        sync: false
      - key: PORT
        value: 10000